### ISSUE TITLE
Co mamy zrobić z tą listą todos?

### ISSUE THREAD

**Issue by Harry180** [mcharytoniuk/how-to-react-workshop#1]
Jak w tytule. Jakoś patrząc na to co już jest w pliku todos.js nie bardzo wiem co mam osiągnąć i zmienić tam :P z tego co zrozumiałem to mieliśmy zrobić żeby się dodawały itemy do listy, ale to już jest :P (może zapisywać polecenia w pliku README.md)

**Comment by mcharytoniuk** [comment]
Wrzuciłem w ten plik 3 rzeczy i jesteście teraz na głębokiej wodzie:
1. dodawanie event listenerów przy pomocy atrybutu React.js ('onClick={this.onFormSubmit}')
2. wywoływanie zenkapsulowanego callbacka z atrybutu 'onSumbit' wewnątrz komponentu React.js
3. mapowanie elementu listy to-do'sow na element HTML

Spraw tylko, żeby lista to-dos'ów dynamicznie renderowała za każdym razem dodany element i tylko tyle, resztę będziemy omawiać szczegółowo. Jeżeli przy tym zrozumiecie jak działa delegacja event listenerów, to będzie dobrze. :D

Pozdro i powodzenia
