### ISSUE TITLE
Co zrobic gdy fetch zwraca Undefined is not a function?

### ISSUE THREAD

**Issue by zangrafx** [mcharytoniuk/how-to-react-workshop#3]
branch: zangrafx
plik:  how-to-react-workshop/web_modules/React/getrandomuser-state.jsx

**Comment by mcharytoniuk** [comment]
To nie problem z `whatwg-fetch`, tylko klasy komponentów powinny dziedziczyć pod `React.Component`, żeby mieć dostęp do metod jak `setState` itp. Kiedy dziedziczysz po innej klasie, wtedy wszystkie jej metody są dostępne w Twoim kodzie, możesz je też nadpisać. Bez tego to zwykły obiekt, który może być całkowicie niezależny od React.js.

Wrzuciłem commit, który pokazuje o co mi chodzi. :)

**Comment by zangrafx** [comment]
Zajebiście, teraz działa :) Wydaje mi się, ze wcześniej też testowałem taki wariant, ale widocznie miałem błąd w innym miejscu. Dzięki!
